### PR TITLE
Fix #279

### LINKED ISSUE #279: Failed to import qiskit_nature.transformers FreezeCoreTransformer
The `transformers` were relocated under `second_quantization` and some deprecation logic was put in place to allow them to be used from the version 0.1.0 location with a deprecation warning. I was looking at some code which was posted describing an issue, written to 0.1.0, and it fails to import the transformers.
```
>>> from qiskit_nature.transformers import FreezeCoreTransformer, ActiveSpaceTransformer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'FreezeCoreTransformer'
```

I do not see any unit tests using the code from the 0.1.0 location to ensure it works. And its not used by any notebooks either where we should catch any compatibility issues.

### PR DESCRIPTION
**Pull request by mrossinek**
### Summary

Closes #279

### Details and comments

I am currently unable to reproduce #279 locally. Hopefully the CI will catch more errors, now that the unittests are duplicated to also test the legacy code location.

### CODE REVIEW

**Comment by woodsp-ibm** [comment]
When I encountered the issue referenced it was under Python 3.6. The unit test here under 3.6 seems to fail similarly from what I can see.

**Comment by woodsp-ibm** [comment]
I see rather than copy the code wholesale you did a new class that subclasses the one that was moved. As long as the new function does not change (I am thinking of discussion where transformers are more applied to properties) I guess that works too.

**Comment by mrossinek** [comment]
> I see rather than copy the code wholesale you did a new class that subclasses the one that was moved. As long as the new function does not change (I am thinking of discussion where transformers are more applied to properties) I guess that works too.

Yes the change of interface will need to be handled in #263. I just noticed that (while I do keep the legacy transformers which take a `QMolecule` as input, I do not keep them as also returning a `QMolecule`. We may need to rethink that before merging that PR.

**Comment by woodsp-ibm** [comment]
>  We may need to rethink that before merging that PR.

Users existing code - where they are using public APIs - ought to continue to work while they have time to transition to the new way. Of course this may have implications to our stack around existing transformers being passed in versus new ones.

**Comment by mrossinek** [comment]
Do you want to merge this PR as is anyways? Or shall I directly update #263 and include the fix for #279 there?

**Comment by woodsp-ibm** [comment]
I think this is an improvement over what is there currently so merging it seems fine. It may not be the final solution, that's fine

**Review by woodsp-ibm — APPROVED** [review]

**Pull request merged**
