### PR TITLE
Use dot rather than obsolete * for composing ops

### PR DESCRIPTION
**Pull request by jlapeyre**
### Summary

Fixes bug reported in #511 in BKSF mapper when processing a number-excitation term

### Details and comments

A test for a bigger molecule, LiH, that previously triggered the bug has been added.
A reno release note has been added.
~A test and a reno will be added.~

### CODE REVIEW

**Review by mrossinek — COMMENTED** [review]
Thanks, @jlapeyre! Did you happen to validate the LiH hamiltonian which you obtained for BKSF with another working source? E.g. the old Aqua code?

**Comment by jlapeyre** [comment]
>  Did you happen to validate the LiH hamiltonian 

@mrossinek , No, all my energy went into pleasing the linters ;). I did look into doing something more like unit testing, eg. test just the function that had the change (for handling number-excitation terms). But, the inputs are rather complicated. (I have another idea to try, though). Regarding Aqua, I recall finding a bug. For the existing H2 test, I compared to OpenFermion. This might be a good option for LiH as well.

**Review by mrossinek — APPROVED** [review]
I guess we can assume that the Hamiltonian is correct. This should probably go into the next bugfix release so I'm approving this.

@woodsp-ibm or @pbark Please also take a look :+1:

**Comment by jlapeyre** [comment]
Merging this as is (after other reviews) seems like a good option. Maybe another PR to improve, or rethink, tests would be good. I also thought about unittesting just the internal method that has been fixed here... that could show that it does what I intended to code (or the original authors did). But not that it gives the correct "physical" answer. Unit testing this way is probably a fair amount of work and would be verbose. On the other hand comparing to openfermion would be much closer to an integration test. The utility would mostly be in the process of writing the test; if they disagree, then we would have to find which (or both) of the packages gives the wrong answer. In fact, I don't think we have anything to convert between openfermion and qiskit-nature, right? Some simple conversion tools would be useful for uncovering potential bugs not only in BKSF, but more widely.

**Review by woodsp-ibm — APPROVED** [review]

**Pull request merged**
