### PR TITLE
Use simpler, more performant construction of array in qubit mapper

### PR DESCRIPTION
**Pull request by jlapeyre**
This constructs a numpy array directly instead of constructing and converting a list.
The construction is both simpler and more performant, although it is unlikely to make the enclosing function faster
in this case.

### CODE REVIEW

**Review by mrossinek — DISMISSED** [review]
Thanks @jlapeyre!

**Comment by woodsp-ibm** [comment]
One could argue that the original construct is a little easier to see that it's an array of False length of num_modes that is wanted. The latter construct does of course give the same but I'd argue it not quite as evident - having code readability is important too and if the construct is not really all that much better, for the size of systems we would be dealing with, where its not really any performance impact, we need to consider that too; Maybe in this case just a comment that went `# [False] * num_nodes` would be helpful

**Comment by jlapeyre** [comment]
But, it's not an array of builtin `False`, it's an array `numpy._bool`. I'm not suggesting premature optimization at the expense of readability. I think it's important to adopt a habit of using a clean, efficient, interface provided by a library, unless there is a good reason to do otherwise.

**Comment by woodsp-ibm** [comment]
I like the np.full better I think. Seeing np.zeros makes me think more numeric, then I have to take notice of the bool type which is why I thought some comment there might be helpful.

**Comment by jlapeyre** [comment]
`full` is slower than `zeros`, but after investigating a bit, I am thinking it might be more readable/coherent. And it's ok since this is not a hot spot.

In many languages booleans are integers. If this were the case in Python, I might argue that `zeros` is correct. But, the Python type ~~system~~ situation is not coherent on this point.
The following all evaluate to `True`:

```python
import numpy as np
from numbers import Integral

isinstance(False, Integral)
not isinstance(np.bool_(False), Integral)
not isinstance(np.bool_(False), np.integer)
not isinstance(np.bool_(False), np.number)
isinstance(int64(1), np.integer)
```

So a Python `bool` is in some sense an integer. And numpy doesn't think `np.bool_` is any kind of number. But, `np.bool_` is still supported by a function that returns an array of "zeros", which is a bit confusing to me. I think `full` avoids this issue.

**Comment by jlapeyre** [comment]
It should also be pointed out that `np.zeros` is used frequently in this context elsewhere in qiskit_nature. Eg, `np.zeros(nmodes, dtype=bool)`

**Review by mrossinek — APPROVED** [review]

**Review by woodsp-ibm — APPROVED** [review]
> It should also be pointed out that np.zeros is used frequently in this context

Oh well, one small step on the road to improving code readability in any case. Thanks John.

**Pull request merged**
