### PR TITLE
Fix dtype bug in BogoliubovTransform

### PR DESCRIPTION
**Pull request by kevinsung**
### Summary
The test I added throws an error without this fix.

### CODE REVIEW

**Review by mrossinek — COMMENTED** [review]
Generally this seems fine to me.

Please update the docstring of the `givens_matrix` method to reflect that a complex matrix will be returned.

<hr/>

I am not sure whether we can consider this a bugfix because this "changes"/constrains the return type of a method. @woodsp-ibm what do you think?

**Comment by kevinsung** [comment]
Done. It's at least a bugfix because it fixes the bug in `BogoliubovTransform` which I added a test for. I guess it's technically a breaking change, though I expect the user impact to be negligible.

**Comment by kevinsung** [comment]
Now that I think of it, I could also fix the bug without modifying the `givens_matrix` function. I think that's preferable, so I'll go ahead and do that.

**Review by mrossinek — APPROVED** [review]
Thanks, this is indeed better :+1:

**Pull request merged**
