### PR TITLE
Gaussian drivers for python 3.9

### PR DESCRIPTION
**Pull request by manoelmarques**

### CODE REVIEW

**Comment by mrossinek** [comment]
Since Gaussian is not available in the CI, could somebody, who has access to a License, verify that this works as expected? At least on one platform?

**Comment by manoelmarques** [comment]
For reference, I tested on the following 64 bits Virtual Machines under Anaconda environment python 3.9. Each driver has the same dependencies as the previous py3.8. It would be good to have an independent test to be sure: 

1. Windows 10 Pro (latest updates)
2. Ubuntu 21.10
3. MacOS Big Sur 11.6

**Review by mrossinek — APPROVED** [review]
I wasn't aware you had the possibility to test these. This is all good then :+1:

**Comment by manoelmarques** [comment]
I have Gaussian installed in all 3 VMs. Lets see if @woodsp-ibm has anything else to say.

**Review by woodsp-ibm — APPROVED** [review]

**Pull request merged**
