### PR TITLE
Change BOPESSasmpler creation first arg. to positional

### PR DESCRIPTION
**Pull request by manoelmarques**

### CODE REVIEW

**Review by mrossinek — APPROVED** [review]
Thanks Manoel! :slightly_smiling_face:

**Review by woodsp-ibm — CHANGES_REQUESTED** [review]
We should not be backporting a breaking change. The BopesSampler ought to be changed so stable tutorials pass - add gss as a deprecated parameter we are changing the name,

**Comment by woodsp-ibm** [comment]
As these changes now exist in #684, without the need of a backport, since the parameter re-naming will be handled via deprecation, is this needed any more?

**Comment by Anthony-Gandon** [comment]
I agree that this backport is not necessary anymore because of how we chose to handle the deprecation of the constructor of BOPESSampler.

**Pull request closed without merging**
