### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by omarcostahamido**
- fixing typo `boostrapping` to `bootstrapping`
- this was detected by [Dennis](https://github.com/Denny-Hwang) on [crowdin](https://crowdin.com/profile/dennis_hwang)

### CODE REVIEW

**Review by pbark — DISMISSED** [review]
Thanks for the change!

**Comment by omarcostahamido** [comment]
@pbark thank you for reviewing it.

**Review by woodsp-ibm — CHANGES_REQUESTED** [review]
The documentation, including notebooks, is run over a spellchecker and it seems that the mispelt bootstrapping was entered into the custom dictionary we have so it ended up passing out spell check. To avoid this the custom dictionary ought to be updated to - just one line needs to be deleted from the .pylintdict https://github.com/Qiskit/qiskit-nature/blob/2d73b969a6086becf39e7fb918e3845a696490b5/.pylintdict#L44 Could you include this in the change too

**Comment by omarcostahamido** [comment]
@woodsp-ibm 
Thank you so much for clarifying that! :)

**Comment by omarcostahamido** [comment]
change done.

**Review by omarcostahamido — COMMENTED** [review]
done

**Review by woodsp-ibm — APPROVED** [review]
@omarcostahamido Thanks for the fix and updating pylintdict too

**Pull request merged**
