### PR TITLE
refactor: move code to new structure

### LINKED ISSUE #701: [refactor] Towards a non-driver focused future
### What should we add?

This Epic outlines the plan for the upcoming restructuring of the entire Qiskit Nature code base.
Separate issues will be created outlining the refactoring plan for each existing module in more
detail. (Some modules/files will not be migrated. See at the bottom of this description.)

## Vision
We are undertaking a step *away* from the existing control flow in which Qiskit Nature uses
`drivers` to handle the electronic structure integral generation by calling other classical codes.
Instead, the plan is to design a code- and language-agnostic description (implemented with HDF5) of
a problem for Qiskit Nature to solve, which the classical code can generate directly.
In this way, the responsibility over the control flow of a calculation is handed over to the
classical codes rather than remaining within Qiskit Nature.

This has multiple benefits, a major one being the immediate availability of iterative embedding
techniques already implemented in classical codes (e.g. CASSCF). In Qiskit Nature's current design,
only CASCI calculations are possible and an implementation of CASSCF would require a custom `driver`
class for each classical code, which is not scalable for the future.

Another issue will be opened in the near future outlining this vision in more detail and discussing
the planned HDF5 file structure.

## Code Structure

With such a drastic change in design, we are taking this opportunity to restructure the code base.
The following structure roughly outlines the intended new structure:
```
qiskit_nature/
    second_quantization/
        algorithms/
            excited_state_solvers/
            ground_state_solvers/
            initial_points/
        circuit/
            library/
                ansatzes/
                initial_states/
        operators/
        mappers/
        hamiltonians/
        properties/
        problems/
        transformers/
        drivers/
```
A more detailed overview including the main classes is given by the following UML:

overview

## Workflow

Someone already familiar with Qiskit Nature, should not have much trouble understanding the
relations outlined by the following class diagram:

relations

Together with this pseudo code, this should roughly outline the intended workflow:
```python
from qiskit_nature.second_quantization.algorithms.ground_state_solvers import (
    GroundStateEigensolver,
    VQEUCCFactory,
)
from qiskit_nature.second_quantization.mappers import JordanWignerMapper, QubitConverter
from qiskit_nature.second_quantization.drivers import HDF5Driver

problem = HDF5Driver("problem_description.hdf5").run()

solver = GroundStateEigensolver(
    VQEUCCFactory(),
    QubitConverter(JordanWignerMapper()),
)

result = solver.solve(problem)
```

More details on the various modules will be provided by the respective issues.

## Unaffected modules
- `constants.py`
- `deprecation.py`
- `exceptions.py`
- `hdf5.py`
- `logging.py`
- `optionals.py`
- `runtime`
- `settings.py`
- `utils`
- `version.py`
- `VERSION.txt`

### PR DESCRIPTION
**Pull request by mrossinek**
### Summary

This is the follow-up to #722 

### Details and comments

This PR uses the approach describes in https://stackoverflow.com/a/44036771 to "copy" files while preserving the blame history in both locations.

:warning: This PR must be merged withOUT squashing all commits (I may however still be able to clean up some of the commits (e.g. the CI changes and `main` merges)

Closes #701 #702 #703 #704 #705 #706 #707 #708 #709 #710 #711

### CODE REVIEW

**Comment by mrossinek** [comment]
FYI: I will be adding commits here until the CI is fixed. Once that is the case, I will rebase to minimize the number of commits being merged into `main`.

**Comment by mrossinek** [comment]
My rebase caused the history preservation to not work as seen here: https://github.com/Qiskit/qiskit-nature/blame/refactor/qiskit_nature/second_q/algorithms/ground_state_solvers/ground_state_eigensolver.py

I will revisit this on Monday to fix that.

**Comment by mrossinek** [comment]
The history preserving aspect of this PR is now working as can be seen under the following two links:
- https://github.com/Qiskit/qiskit-nature/blame/refactor/qiskit_nature/second_q/algorithms/excited_states_solvers/__init__.py
- https://github.com/Qiskit/qiskit-nature/blame/refactor/qiskit_nature/algorithms/excited_states_solvers/__init__.py

**Comment by mrossinek** [comment]
I also marked this PR to be closing all of the code relocation issues. I will open separate issues for the planned refactorings within the modules in the near future :+1:

**Comment by ElePT** [comment]
Yay! Git blame works for both the old and the new modules!

**Comment by ElePT** [comment]
One small comment, the tutorials I removed (5,6 and 9) are still removed in this PR. It doesn't make sense to migrate them, but shouldn't we keep the old version of these together with the old version of the repo until we fully deprecate it?

**Comment by mrossinek** [comment]
> One small comment, the tutorials I removed (5,6 and 9) are still removed in this PR. It doesn't make sense to migrate them, but shouldn't we keep the old version of these together with the old version of the repo until we fully deprecate it?

Hm that's a good point actually. For the docs I decided (based on a discussion with @manoelmarques and previous input from @woodsp-ibm) that only the new code is documented in the API (i.e. the old code no longer has API documentation). Nonetheless, I agree that it makes sense to keep the legacy tutorials in place. I will re-add those in an upcoming commit :+1: 

> I also took a quick look at the docs and they seem ok to my untrained eye.

Thanks :+1:

**Review by manoelmarques — APPROVED** [review]

**Pull request merged**
