### PR TITLE
Set main_property_name through the constructor of BaseProblem

### PR DESCRIPTION
**Pull request by a-matsuo**
### Summary
Set `main_property_name` thought  the constructor of `BaseProblem` instead of setting in each sub class. 

Based on this discussion https://github.com/Qiskit/qiskit-nature/pull/620#discussion_r881292144 .

- [x] `ElectronicStructureProblem`
- [x] `VibrationalStructureProblem`

### CODE REVIEW

**Comment by woodsp-ibm** [comment]
It looks good to me. If a third party happened to subclass BaseProblem and use the old way, the code would still work as the instance var is the same name, so setting it directly still works. (Your LatticeProblem with the code in the PR as it current stands still works right!)

Since we really need the sub-class to set the main property name I would almost argue that it should not have a default value. But that would require more change to do that, so at present I think what you have done here suffices.

This could be merged before the LatticeProblem PR and the problem there updated and then merged - or I guess you marked this as draft and listed the LatticeProblem in here as you prefer to merge the LatticeProblem first and then change its problem class via this PR to keep the changes together. I think I am fine either way.

**Comment by a-matsuo** [comment]
Actually, I was thinking this to be merged after the LatticeProblem PR. I'am fine either way as well. If we merge this PR first, I need to change the LatticeProblem PR based on this change. Do you have have any preference? @mrossinek

**Comment by woodsp-ibm** [comment]
@a-matsuo The only reason I was thinking the LatticeProblem PR might be updated/merged after this was merged that this PR is easy to review, seems what we agreed etc and looks good already - its just sat waiting for the LatticeProblem PR to be merged right, when it could be approved/merged already I think and the LatticeProblem fixed up afterwards. But as I said I am fine either order, but the LatticeProblem still needs a final review.

**Review by mrossinek — APPROVED** [review]
I agree, it does not really make a difference in which order we apply these changes. I'm going to approve this as is and let you take the decision :+1: 
I don't think we need a release note for this, do we? @woodsp-ibm

**Comment by woodsp-ibm** [comment]
As I noted above ` If a third party happened to subclass BaseProblem and use the old way, the code would still work as the instance var is the same name, so setting it directly still works.` Since this is the case, and since its unlikely anyone has even done this, I think this is fine
 without a release note.

**Comment by a-matsuo** [comment]
@woodsp-ibm @mrossinek Thank you for reviewing! I will modify the LatticeModelProblem PR based on this change.

**Pull request merged**
